### ISSUE TITLE
Also convert "commercial use"

### ISSUE THREAD

**Issue by oliverklee** [oliverklee/ext-csv_to_openimmo#31]
Nutzungsart ist in der Spalte C / bzw. Nr. 3.

Auswahlliste:
- Garage
- Wohnraum

Aus der Mail:

> Haustyp_Feld_3 (1):
>
> Es wurde ein neuer Hautyp „Wohnung“ (id=6) importiert (bzw. angelegt). In der CSV steht aber „Wohnraum“ (analog zum bereits existierenden Haustyp im Backend). Der Datensatz wurde mit dem importierten Haustyp „Wohnung“ (id=6) verknüpft und taucht somit nicht im Frontend auf (für die Ausgabe im Frontend ist ein SQL-Filter auf den Haustyp „Wohnraum“ (id=1) gesetzt.
>
> Haustyp_Feld_3 (2):
> Der importierte Tiefgaragenstellplatz ist ebenfalls mit dem Haustyp „Wohnung“ (id=6) verknüpft, obwohl in der CSV „Garage“ steht. Im Backend existiert aber ein Haustyp „Garage“ (id=4).

Hier sollten wir noch herausfinden, welche exakten Werte im CSV stehen können.

In OpenImmo gibt es bei "nutzungsart":
- WOHNEN
- GEWERBE
- ANLAGE
- WAZ

**Comment by oliverklee** [comment]
In OpenImmo gibt es noch das Feld objektkategorie > objektart mit diesen Werten:

```xml
				<xsd:element ref="zimmer" maxOccurs="unbounded"/>
				<xsd:element ref="wohnung" maxOccurs="unbounded"/>
				<xsd:element ref="haus" maxOccurs="unbounded"/>
				<xsd:element ref="grundstueck" maxOccurs="unbounded"/>
				<xsd:element ref="buero_praxen" maxOccurs="unbounded"/>
				<xsd:element ref="einzelhandel" maxOccurs="unbounded"/>
				<xsd:element ref="gastgewerbe" maxOccurs="unbounded"/>
				<xsd:element ref="hallen_lager_prod" maxOccurs="unbounded"/>
				<xsd:element ref="land_und_forstwirtschaft" maxOccurs="unbounded"/>
				<xsd:element ref="parken" maxOccurs="unbounded"/><!--$V123-->
				<xsd:element ref="sonstige" maxOccurs="unbounded"/>
				<xsd:element ref="freizeitimmobilie_gewerblich" maxOccurs="unbounded"/>
				<xsd:element ref="zinshaus_renditeobjekt" maxOccurs="unbounded"/>
```

**Comment by jpeters78** [comment]
- Garage
- gewerbliche Nutzung
- Stellplatz
- Wohnraum

**Comment by oliverklee** [comment]
Ich habe es gerade noch einmal im Detail nachgeschaut: So kommt der Haustyp beim OpenImmo-Export der realty-Extension zustande:

Der Import nimmt das erste Unterelement von objektkategorie > objektart (z.B. "wohnung" und ersetzt den ersten Buchstaben durch einen Großbuchstaben (in diesem Fall wird darauf "Wohnung"). Falls das XML-Element dann noch Attribute hat, werden diese kommagetrennt ucfirst angehängt. Daraus würde dann beispielsweise ein Titel wir "Wohnung: Dachgeschoss, Maisonette". Dann legt der Import einen entsprechenden Haustyp-Datensatz mit diesem Titel an, falls er noch nicht existiert, und weist dem Immobilienobjekt diesen Haustyp zu.

Da wir mit dem CSV-Converter OpenImmo als gemeinsames Austauschformat haben, sind für den  Haustyp beim Import auf die in OpenImmo verfügbaren Haustypen beschränkt, also auf diese hier:
- zimmer
- wohnung
- haus
- grundstueck
- buero_praxen
- einzelhandel
- gastgewerbe
- hallen_lager_prod
- land_und_forstwirtschaft
- parken
- sonstige
- freizeitimmobilie_gewerblich
- zinshaus_renditeobjekt

Wenn in der CSV-Datei die Schreibweise von dieser abweicht, ist es wichtig, dass ich die genaue Schreibweise weiß, damit ich das im Converter entsprechend einbauen kann.

**Comment by oliverklee** [comment]
Zurzeit ist beim CSV-Converter der Haustyp "Wohnung" hartkodiert (ich hatte im Hinterkopf, dass ursprünglich nur Wohnungen importiert werden sollten, kann mich da aber durchaus irren).

**Comment by oliverklee** [comment]
Der Wohnungstype wird zurzeit vom OpenImmo-Import der realty-Extension noch gar nicht importiert.

**Comment by oliverklee** [comment]
Die Nutzungsart in OpenImmo kann diese Werte mit Mehrfachauswahl haben:
- Wohnen (Pflichtangabe)
- Gewerbe (Pflichtangabe)
- Anlage (optional)
- WAZ (optional)

Der OpenImmo-Import importiert die Nutzungsarten dabei als Freitext, wobei die Werte ucfirst und kommagetrennt werden.

@jpeters78, @vmAKT Haben wir im CSV Daten, anhand derer der CSV-Converter bestimmen kann, ob ein Objekt ein Wohnobjekt und/oder ein Gewerbeobjekt ist, damit die Pflichtangaben im OpenImmo korrekt sind?

**Comment by vmAKT** [comment]
Das Feld Nutzungsart ist nicht vorhanden/wird nicht genutzt. Stattdessen ist für uns "Haustyp" relevant.

Anhand vom Haustyp kann bestimmt werden, ob es ein Wohn- oder Gewerbeobjekt bzw. Stellplatz ist. Die Schreibweise kläre ich mit dem Kunden.

**Comment by vmAKT** [comment]
Ist diese Frage noch offen? Feld 3 im CSV bestimmt das. Oder habe ich etwas falsch verstanden?

**Comment by oliverklee** [comment]
Die Frage nach den Nutzungsarten habe ich in das Ticket #49 ausgelagert.
