### ISSUE TITLE
Decide on an encoding for the CSV file

### ISSUE THREAD

**Issue by oliverklee** [oliverklee/ext-csv_to_openimmo#37]
UTF-8, ISO-8859-15 or Windows-1252?

**Comment by oliverklee** [comment]
Wir benutzen UTF-8.

**Comment by oliverklee** [comment]
@vmAKT, @peters78 Ich nehme alles zurück. Das neue CSV ist ebenfalls ISO8859-15, und ich hatte mich geirrt in der Annahme, dass sie in UTF-8 ist.

**Comment by vmAKT** [comment]
Der Kunde nutzt ISO8859-15, müsste ggf. eine Änderung beim Softwarehersteller betragen, wenn UTF-8 gewünscht ist. --> Besser bei ISO bleiben.
