### ISSUE TITLE
Convert the elevator field

### ISSUE THREAD

**Issue by jpeters78** [oliverklee/ext-csv_to_openimmo#43]
in the csv file the string 'vorhanden' is set, but the realty field 'elevator' is empty after openImmoImport

**Comment by oliverklee** [comment]
Wir brauchen dazu im OpenImmo `ausstattung` > `fahrstuhl` mit dem Attribut `personen="true"`.

**Comment by vmAKT** [comment]
Heißt das, dass in der CSV-Tabelle eine Spalte mit dem Inhalt "ausstattung" und daneben eine Spalte mit der Ausprägung "fahrstuhl" eingegeben werden muss? Das ist etwas zu technisch für mich.

**Comment by oliverklee** [comment]
@vmAKT Nein, das war nur eine Notiz an mich, wo der Converter die Daten in der OpenImmo-XML-Struktur speichern soll.
