### ISSUE TITLE
realty heating_types are set incorrectly after openImmoImport 

### ISSUE THREAD

**Issue by jpeters78** [oliverklee/ext-csv_to_openimmo#44]
csv:
Fernwärme

should be marked as checked:
- Fernwärme

currently marked as checked:
- Fernwärme
- Zentralheizung
- Fußbodenheizung
- Etagenheizung
- Ofen

**Comment by vmAKT** [comment]
Wir haben gestern getestet und der Bug ist noch vorhanden. Ist die Änderung in der offiziellen Version der realty schon übernommen?

**Comment by oliverklee** [comment]
Ja, ist er (auf GitHub; ich habe noch nicht ins TER releast). Mit welcher Version der realty-Extension haben Sie denn getestet?

**Comment by vmAKT** [comment]
Das vermutlich noch die alte realty-Version.

**Comment by oliverklee** [comment]
@vmAKT Könnten Sie bitte noch mit der aktuellen realty-Version testen, ob das Problem damit behoben ist? Vielen Dank!
