### ISSUE TITLE
Also use "parking" for the object type

### ISSUE THREAD

**Issue by vmAKT** [oliverklee/ext-csv_to_openimmo#46]
Ist es möglich, dass aus Garage/Stellplatz allgemein „Parken“ wird?

> Was konkret ist hier gemeint? Geht es „nur“ um die Umbenennung der Werte in der Auswahlliste im Typo3 BackOffice, oder dass wir beim Export im Feld Nutzungsart (3) anstatt „Stellplatz“ oder „Garage“ den Wert „Parken“ liefern?

**Comment by oliverklee** [comment]
> Ist es möglich, dass aus Garage/Stellplatz allgemein „Parken“ wird?

@vmAKT Meinen Sie das Label des Feldes in der Realty-Extension? Oder beziehen Sie sich auf etwa anders?

**Comment by vmAKT** [comment]
Ich hatte es so verstanden, dass es beim Haustyp (Feld 3) besser wäre, wenn im CSV statt Garage oder Stellplatz (zusätzlich zu den Optionen Wohnung und Gewerbefläche), einfach nur Parken steht. Denn neben Wohnungen und Gewerbeflächen werden auch Stellplätze vermietet.

**Comment by oliverklee** [comment]
Notiz aus dem Telefonat gerade: Wenn im CSV "Stellplatz" oder "Garage" steht, soll im OpenImmo daraus die Objektart "Parken" werden. Wir werden das dann nicht weiter unterteilen (also nicht "Tiefgarage" etc.)
