### ISSUE TITLE
Convert balcony and patio as one field

### ISSUE THREAD

**Issue by vmAKT** [oliverklee/ext-csv_to_openimmo#47]
Ist es möglich dass Balkon/Terasse in je einem Feld im CSV aufgeführt werden?

> Leider nicht möglich! Bei uns im ERP System heißt das Merkmal auch Balkon/Terrasse mit Werten vorhanden/nicht vorhanden. Wir unterscheiden hier also nicht zw. Balkon und Terrasse und können es daher auch nicht getrennt liefern.

- Können Sie uns hierzu eine Lösung vorschlagen?

**Comment by oliverklee** [comment]
@vmAKT In der Realty-Extension ist das eh nur ein einziges Feld "Balkon/Terrasse". Die Haupt-Baustelle ist also das OpenImmo-Format zwischen Wodis und der Realty-Extension.

Beim OpenImmo-Format gab es bis einschließlich Version 1.2.3 ein Feld "anzahl_balkon_terrassen", das in Version 1.2.4 entfernt wurde und ab Version 1.2.3 durch die zwei Felder "anzahl_balkone" und "anzahl_terrassen" ersetzt wurde. (Aktuell ist OpenImmo Version 1.2.7b.)

Als einen der automatisierten Tests der CSV-Import-Extension benutze ich einen Check, ob das generierte OpenImmo-XML mit der aktuellen OpenImmo-Schema-Datei valide ist.

Ich werde daher mal testen, ob das XML auch dann valide ist, wenn das Feld "anzahl_balkon_terrassen" vorhanden ist, und bei Erfolg dann dieses Feld importieren. Die Realty-Extension werde ich dann entsprechend anpassen, dass sie sowohl die alten als auch die neuen Felder importieren kann.

**Comment by oliverklee** [comment]
@vmAKT Könnten Sie bitte beim Kunden nachfragen, ob es eventuell inzwischen eine neuere Version von Wodis gibt, die die Felder trennt?

**Comment by vmAKT** [comment]
Das ist leider nicht möglich. Der Kunde ist frei in der Anlage und Strukturierung der Merkmale. Ein neues Merkmal „Terrasse“ in wodis wäre möglich, allerdings wäre es ein riesen Aufwand diese Information für 14.000 Objekte zu pflegen/zu erfassen im Vergleich zum Nutzen.
