### ISSUE TITLE
Convert the floor as a free-text field

### ISSUE THREAD

**Issue by vmAKT** [oliverklee/ext-csv_to_openimmo#48]
Etage ist im OpenImmo ein Zahlenfeld, daher dies im CSV berücksichtigen und entsprechend anzupassen (0 = Erdgeschoss, 1 = 1. Stock, ...)

> Das Feld „Etage“ haben wir leider nicht als Zahlenfeld. Ein Mapping ist nicht 100% möglich, da wir u.a. Werte wie „Dachgeschoss“ oder „Souterrain“ haben. Warum nicht Etage leer lassen und wie gehabt das Feld „Wohnungstyp“ gebrauchen? Ist nicht ganz sauber, wäre aber sicherlich der geringste Aufwand. Was spräche dagegen?

**Comment by oliverklee** [comment]
> Warum nicht Etage leer lassen und wie gehabt das Feld „Wohnungstyp“ gebrauchen? Ist nicht ganz sauber, wäre aber sicherlich der geringste Aufwand. Was spräche dagegen?

@vmAKT Von mir aus spricht nichts dagegen. Ich müsste dann wissen, in welchem Feld das steht und welche Werte genau dort vorhanden sein werden. Zur Info: Diese Werte sind (inhaltlich) in OpenIMmo für den Wohnungstyp möglich, und nur diese kann der CSV-Converter daher in OpenImmo konvertieren:

- DACHGESCHOSS
- MAISONETTE
- LOFT-STUDIO-ATELIER
- PENTHOUSE
- TERRASSEN
- ETAGE
- ERDGESCHOSS
- SOUTERRAIN
- APARTMENT
- FERIENWOHNUNG
- GALERIE
- ROHDACHBODEN
- ATTIKAWOHNUNG
- KEINE_ANGABE

**Comment by vmAKT** [comment]
Die Werte sind in Typo3 (1. Etage, 1. Obergeschoss, 1./2. Obergeschoss, 1. Obergeschoss / Dachgeschoss, 1. Untergeschoss, 10. Etage, 11. Etage, 12. Etage, ...) angelegt, allerdings passt das nicht mit den Werten, die OpenImmo vorgibt zusammen. Haben Sie hier vielleicht noch einen Lösungsvorschlag?

**Comment by oliverklee** [comment]
Notiz vom Telefonat gerade: Ich schaue mal, über welches OpenImmo-Feld wir das möglicherweise abdecken können.

**Comment by oliverklee** [comment]
Das OpenImmo-Feld, das sowohl ein Freitextfeld ist, am besten passt und das der OpenImmo-Import in die Realty-Extension importiert, ist das Feld "Lage". Ich werde das daher entsprechend im Converter ergänzen.

**Comment by oliverklee** [comment]
Ah, die Lage haben wir schon als separates Feld. Ich benutze daher das Feld "Sonstiges" stattdessen.
