### ISSUE TITLE
Bug: Gewerbefläche als Wohnung gekennzeichnet

### ISSUE THREAD

**Issue by vmAKT** [oliverklee/ext-csv_to_openimmo#58]
Beim Import ins Typo3 wurde eine Gewerbefläche als Wohnung im Feld Haustyp gekennzeichnet. Die Nutzungsart war mit "gewerbliche Nutzung" ausgefüllt.

Ziel ist, dass am Ende im Typo3 "Gewerbefläche" steht. Muss die CSV-Datei entsprechend angepasst werden? Was muss dort stehen, damit es klappt bzw. wo liegt der Fehler?

**Comment by oliverklee** [comment]
@vmAKT Haben Sie mit der aktuellsten Version der beiden Extensions (realty. csv_to_openimmo) von GitHub getestet? Falls nein, tritt das Problem mit der aktuellesten Version immer noch auf?

**Comment by vmAKT** [comment]
Bei der realty bin ich mir nicht sicher, die csv_to war die neueste Verison.

**Comment by oliverklee** [comment]
@vmAKT Könnten Sie bitte noch mit der aktuellen realty-Version testen, ob das Problem damit behoben ist? Vielen Dank!

**Comment by oliverklee** [comment]
Duplikat von #61.
