### ISSUE TITLE
Löschen von nicht wieder importierten Wohnungen funktioniert nicht

### ISSUE THREAD

**Issue by vmAKT** [oliverklee/ext-csv_to_openimmo#59]
Beim Extension-Manager haben wir „Allow deletion records“ aktiviert, allerdings bleiben bereits importierte Wohnungen beim nächsten Import online, obwohl sie im neuen Import nicht mehr enthalten sind.

**Comment by oliverklee** [comment]
ToDo für mich: Wahrscheinlich (nach Feedback) Schalter einbauen, wie aggressiv/konservativ gelöscht werden soil.

**Comment by vmAKT** [comment]
Ergänzung: 
--> Beim Löschen sollen nur die Objekte geprüft und gelöscht werden, die sich in dem Ordner mit dieser PID befinden: [basic.pidForRealtyObjectsAndImages]
Weitere Objekte, die in anderen PIDs gespeichert sind, müssen von dieser Regel ausgeschlossen sein!

**Comment by vmAKT** [comment]
Ergänzung zwei: Wohnungen können auch manuell angelegt werden. Die Wohnungen, die über die Schnittstelle kommen, dürfen die manuellen nicht überschreiben. Wir lösen das über separate Ordner.

**Comment by oliverklee** [comment]
#65 stellt den Übertragungstype der konvertierten OpenImmo-Datei von "Teilübertragung" auf "Vollübertragung" um. Ich passe gleich noch die realty-Extension an.

**Comment by oliverklee** [comment]
https://github.com/oliverklee/ext-realty/pull/43 ist der realty-Teil.

**Comment by oliverklee** [comment]
@vmAKT Bitte unbedingt auch die realty aktualisieren. (Falls Sie nur die csv_to_openimmo aktualisieren, kann es sein, dass sonst beim nächsten Import auch die manuell eingetragenen Objekte futsch sing.)
