### ISSUE TITLE
Warmmiete anzeigen lassen

### ISSUE THREAD

**Issue by vmAKT** [oliverklee/ext-csv_to_openimmo#60]
Nach nochmaliger Prüfung hat sich herausgestellt, dass in der Vergangenheit das Label für Courtage via extTables.php in Warmmiete umbenannt wurde. Aus unserer Sicht können wir das beibehalten (es wird kein neues Feld Warmmiete benötigt). Wichtig ist nur, dass dann das Feld provision im CSV-Konverter mit der Gesamtmiete gemappt wird und dass das Feld provision in der realty-Listenansicht ausgegeben werden kann (via Marker).

**Comment by vmAKT** [comment]
Diesen Punkt bitte auch in der Listenansicht nachrüsten.

**Comment by vmAKT** [comment]
Auch bei Stellplätzen soll die Warmmiete ausgegeben werden.

**Comment by oliverklee** [comment]
ToDo an mich: Feld hinzufügen, importieren, im FE in der Übersichtstabelle anzeigen und Marker für die Listenansicht bereitstellen.

**Comment by oliverklee** [comment]
Teil 1: Feld hinzufügen: https://github.com/oliverklee/ext-realty/pull/40

**Comment by oliverklee** [comment]
Teil 2: Warmmiete importieren: https://github.com/oliverklee/ext-realty/pull/41

**Comment by oliverklee** [comment]
@vmAKT Der Marker in der Listenansicht für die Warmmiete ist `###RENT_WITH_HEATING_COSTS###`.

**Comment by oliverklee** [comment]
Teil 3: Warmmiete im FE anzeigen und Marker für die Listenansicht bereitstellen: https://github.com/oliverklee/ext-realty/pull/42

**Comment by oliverklee** [comment]
Damit wären die wichtigsten Punkte erledigt. Zum FE-Editor füge ich das Feld später noch hinzu (ohne Berechnung für Sie).
