### ISSUE TITLE
In der CSV Feld 3 auf Nutzungsart mappen und Converter anpassen

### ISSUE THREAD

**Issue by vmAKT** [oliverklee/ext-csv_to_openimmo#61]
> Vitali. Nutzungsart: Gewerbe-Angebote werden auf der Wohnungsseite dargestellt. Über welches Feld wird aktuell sichergestellt, das Wohnungen auf der Wohnungsseite und Gewerbe auf der Gewerbeseite erscheinen?

Oliver. Das ist eine Sache der Konfiguration der Site. Ich kenne Ihre Site nicht
und kann daher nichts dazu sagen. Wenn Sie mir einen Admin-BE-User
erstellen, kann ich aber gerne für Sie nachschauen.

> Vitali. Wir filtern nun über die Nutzungsart und nicht mehr über den Haustyp. In der CSV muss daher das Feld 3 auf Nutzungsart gemappt werden. Könnten Sie hier den Converter anpassen?

**Comment by oliverklee** [comment]
@vmAKT Zurzeit setzt der Converter das so um:

- Nutzungsart "Wohnen" ist immer "false".
- Nutzungsart "Gewerbe" ist "true", falls in Feld 3 "gewerbliche Nutzung" steht, ansonsten ist es "false".

Gibt es in Feld 3 noch andere Texte, die dazu führen sollen, dass das Objekt die Nutzungart "Gewerbe" erhält?

**Comment by vmAKT** [comment]
Feld 3 enthält noch den Wert "Parken".

**Comment by oliverklee** [comment]
Notiz am mich: Filter im Plugin anschauen, warum das Objekt bei Wohnen zu sehen ist und nicht bei Gewerbe.

**Comment by vmAKT** [comment]
Wir hätten gerne, dass auch bei Parken und Wohnen das Feld Nutzungsart gefüllt wird (damit einheitlich nach Nutzungsart gefiltert werden kann). Screenshot:
![bildschirmfoto 2018-08-24 um 15 05 37](https://user-images.githubusercontent.com/39700055/44587637-d63b5f80-a7b3-11e8-9fe6-09e48aac5caa.png)

**Comment by oliverklee** [comment]
@vmAKT Ich hatte von unserem Telefonat mitgenommen, dass ich mir die Konfiguration des Filters in Ihrer Installation mal anschauen sollte. Ist das noch aktuell? Ich glaube, ich habe von Ihnen dazu noch keine BE-Zugangsdaten erhalten.

**Comment by oliverklee** [comment]
@vmAKT Dafür bräuchte ich von Ihnen die Texte, die im CSV in Spalte 3 stehen können und die zur Nutzungsart Wohnen führen sollen.

Wegen Parken: In OpenImmo gibt es keine Nutzungsart "Parken". Allerdings werden die Texte "Stellplatz" und "Garage" in Spalte 3 jetzt schon erkannt, sodass dann die Objektart auf "Parken" steht. Sie könnten für die Parkobjekte also danach filtern.

**Comment by vmAKT** [comment]
Bei "Parken" hat auch alles funktioniert, die Filterung hat auch geklappt. Lediglich die Nutzungsart im Typo3 wurde nicht einheitlich bei allen Objekten ausgefüllt.

Texte für Nutzungsart Wohnen: "Wohnung" steht in der CSV in Feld 3.

**Comment by oliverklee** [comment]
@vmAKT Ja, siehe #69.
