### ISSUE TITLE
Exakte Adresse im Frontend anzeigen lassen

### ISSUE THREAD

**Issue by vmAKT** [oliverklee/ext-csv_to_openimmo#62]
> Was ist nötig, damit via Import die Option ‚Exakte Adresse im Frontend anzeigen’ standardmäßig gesetzt wird?

Dieses Feld wird zurzeit schon aus OpenImmo importiert. Es fehlen also
diese beiden Dinge:

1.a) entweder das Feld wird noch zum CSV-Export hinzugefügt und enthält
dann den Wert "1", "ja", "true" o.ä., und Sie teilen mir mit, welches
Feld dies ist
1.b) oder Sie sagen, dass das Feld immer gesetzt sein soll und sich dies
auch in Zukunft voraussichtlich nicht ändern wird
2. Dann würde ich den Konverter entsprechend anpassen, dass er das Feld
mit konvertiert (Variante a) oder hartkodiert immer auf "Adresse
anzeigen" setzt

Welche Variante hätten Sie gerne?

> Wir nehmen die Variante 1b.

**Comment by oliverklee** [comment]
Kümmere ich mich drum.
