### ISSUE TITLE
Warmmiete wird nicht immer angezeigt

### ISSUE THREAD

**Issue by vmAKT** [oliverklee/ext-csv_to_openimmo#67]
Marker für Warmmiete ist im Template eingebaut (Subpart LIST_ITEM). Erscheint im Frontend aber nur im Zusammenspiel mit dem SQL-Filter house_type IN (1,5), wobei 1 =Wohnraum und 5 = Wohnung ist. Bleibt der SQL-Filter leer erscheint die Warmmiete NICHT. Mit dem SQL-Filter house_type IN (1,3) erscheint die Warmmiete auch nicht, 3 = Stellplatz. Hinweis: Bei den Stellplätzen heißt Warmmiete "Gesamtmiete".

Sie können dazu gerne im System nachsehen.

**Comment by oliverklee** [comment]
@vmAKT Tritt das Problem bei demselben Objekt und mit demselbem HTML-Template auf abhängig davon, was Sie im SQL-Filter stehen haben?

Bei welchem Objekten (mit welcher UID) tritt das Problem genau auf?

Haben Sie schon geschaut, ob das Feld "Warmmiete" bei den entsprechenden Objekten gefüllt ist, wenn Sie es im BE bearbeiten?

Wenn ich in den Ordner "OpenImmo Imports" schaue, haben nur diese Objekte eine Nicht-Null-Warmmiete:
- 587 JP TEST 1-Raum-Wohnung in Jena-Nord
- 585 Gewerberäume in Blankenhain JP1
- 586 JP Geben Sie Ihrem Auto hitzefrei! Wir schenken Ih...
- 596 Gewerberäume in Blankenhain JP2

Die anderen Objekte haben eine Warmmiete von 0,00€ (also keine Warmmiete), sodass im FE keine Warmmiete angezeigt wird.

**Comment by jpeters78** [comment]
Genau diese Objekte haben wir auch für unsere Tests herangezogen. Je nach gesetztem SQL-Filter wird die Warmmiete bei diesen Objekten ausgespielt oder eben nicht (betrifft nur die Listenansicht).

**Comment by jpeters78** [comment]
Wenn man bei dem älteren Objekt allerdings die Warmmiete ausfüllt, erscheint bei allen Objekten im Frontend wieder die Warmmiete (Gesamtmiete). Bedingung für die Ausgabe im Frontend ist also scheinbar, dass alle abzubildenden Objekte in der Liste einen Wert größer 0 im Feld Warmmiete haben müssen.

Kann das abgestellt werden oder muss dafür gesorgt werden, dass allen Objekten ein Wert zugewiesen wird?

(Vermutlich spielt der SQL-Filter keine Rolle)

**Comment by oliverklee** [comment]
@jpeters78 Genau, der SQL-Filter sollte keine Rolle spielen, weil der nur auswählt, welche Objekte zu sehen sind, aber nicht, welche Felder wie zu sehen sind. Ich vermute, dass da einige Subparts nicht automatisch wieder sichtbar gemacht werden, sobald sie einmal versteckt werden. Schaue ich mir gleich an.

Ich schließe dieses Ticket hier und mache dann hier im realty-Projekt weiter: https://github.com/oliverklee/ext-realty/issues/44

**Comment by jpeters78** [comment]
Ja, es funktioniert. Ich habe das Feld Warmmiete für ein Objekt geleert. Bei den übrigen Objekten wird weiterhin die Warmmiete ausgegeben.

**Comment by oliverklee** [comment]
@jpeters78 Super, danke für die Rückmeldung!
