### ISSUE TITLE
Bildansicht wenn das Objekt nur ein Bild hat

### ISSUE THREAD

**Issue by vmAKT** [oliverklee/ext-csv_to_openimmo#68]
Im HTML-Template gibt es für die Liste zwei Marker:
IMAGE_LEFT | IMAGE_RIGHT
 
Darstellung im Frontend: 
IMAGE_LEFT (Außen) | IMAGE_RIGHT (Grundriss)             => 1. Objekt hat zwei Bilder
IMAGE_LEFT (leer) | IMAGE_RIGHT (Außen)                      => 2. Objekt hat ein Bild
 
Wenn im Template für die Liste der Marker IMAGE_LEFT gesetzt wird, fehlt beim 2. Objekt das Bild gänzlich. Wenn im Template für die Liste der Marker IMAGE_RIGHT gesetzt wird, wird beim 1. Objekt der Grundriss angezeigt, beim 2. Objekt die Außenansicht.
 
Beides funktioniert für jenawohnen nicht. Der Kunde möchte immer die Außenansicht in der Liste zeigen. Im Datensatz steht die Außenansicht immer an oberster Stelle.

Gäbe es dafür eine Lösung?

**Comment by oliverklee** [comment]
Die Logik, wie die Bilder zugewiesen werden, orientiert sich an der Reihenfolge der Bilder und daran, dass für ein sauberes Layout bei nur einem Bild das Bild rechts stehen sollte. Also so:

- keine Bild vorhanden: kein Bild im HTML
- ein Bild vorhanden: rechtes Bild damit gefüllt, linkes Bild leer
- (mindestens) zwei Bilder vorhanden: erstes Bild links, zweites rechts

Eine sauberere Lösung könnte so aussehen, dass null bis zwei Bilder im HTML stehen (abhängig davon, wie viele Bilder dem Objekt zugeordnet sind), die Reihenfolge der Bilder im HTML dann immer der im Objekt entspricht, und die Positionierung wäre dann per Floats o.ä. Die Marker sollten dann entsprechend nicht IMAGE_LEFT und IMAGE_RIGHT sein, sondern eher IMAGE_1 und IMAGE_2.

@vmAKT Was halten Sie von dieser Idee? Und wenn die Extension die Marker IMAGE_1 und IMAGE_2 bereit stellt, wären Sie dann bereit, die nötigen Anpassungen zum HTML und CSS zu liefern, damit ich sie in die offizielle Version übernehmen kann? (Notfalls kann ich das auch selbst machen. Es ginge nur wahrscheinlich schneller, wenn das jemand machte, der mehr auf FE spezialisiert ist als ich es bin.)

**Comment by jpeters78** [comment]
Wir lösen das Problem erstmal über zwei verschiedene HTML-Templates.

**Comment by oliverklee** [comment]
Okay. Dann schließe ich das Ticket.
