### ISSUE TITLE
Stadtteil soll nicht im Frontend ausgegeben werden

### ISSUE THREAD

**Issue by jpeters78** [oliverklee/ext-csv_to_openimmo#71]
Stadtteil ist Teil des Markers ###ADDRESS###. Wie kann er ausgeklammert werden?

**Comment by oliverklee** [comment]
Hallo @jpeters78, könnten Sie Tickets, die nur die realty-Extension betreffen und nicht den CSV-nach-OpenImmo-Converter, bitte unter https://github.com/oliverklee/ext-realty/issues eintragen und nicht hier? Dann ist alles schon direkt am richtigen Ort. Vielen Dank! :-)

**Comment by oliverklee** [comment]
Die Teile der Adresse, die im FE dargestellt werden, sind zurzeit hartkodiert:
https://github.com/oliverklee/ext-realty/blob/master/Model/class.tx_realty_Model_RealtyObject.php#L1973

1. Straße, falls detailliert Anzeige der Adresse im Objekt eingeschaltet ist
2. PLZ, Ort, Ortsteil
3. Land

Ich empfehle, dass der Kunde bei den Objekten, bei denen kein Ortsteil dargestellt werden soll, den Ortsteil leer lässt. Alternativ kann ich die Teile der Adresse auch per TypoScript konfigurierbar machen (was Entwicklungsaufwand wäre).

**Comment by oliverklee** [comment]
Ich habe das Ticket hier geschlossen, weil das die realty-Extension betrifft und wir bei Bedarf die Diskussion dort weiterführen sollten.
