### ISSUE TITLE
Wie kann die Absender-Email-Adresse geändert werden

### ISSUE THREAD

**Issue by jpeters78** [oliverklee/ext-csv_to_openimmo#72]
Problem (realty: Kontaktformular):

Die Mails der Anfragenden werden von der Firewall geblockt. Grund hierfür: als Absender-Mail steht in der Admin-Mail die Mail-Adresse des Users. Es muss möglich sein diese via TypoScript-Konfiguration zu überschreiben. Reply-To soll aber weiterhin die User-Mail-Adresse sein.

**Comment by oliverklee** [comment]
Hallo @jpeters78, könnten Sie Tickets, die nur die realty-Extension betreffen und nicht den CSV-nach-OpenImmo-Converter, bitte unter https://github.com/oliverklee/ext-realty/issues eintragen und nicht hier? Dann ist alles schon direkt am richtigen Ort. Vielen Dank! :-)

**Comment by oliverklee** [comment]
@jpeters78 Mit etwas Entwicklungsaufwand (sehr wahrscheinlich unter unter 4 Stunden) kann ich das so umbauen:

- Als Absenderadresse wird die im Install-Tool eingetragene defaultMailFromAddress und defaultMailFromName benutzt, sodass es keine Probleme mit der Firewall mehr gibt.
- Beim jedem Mailversand wird die im Install-Tool eingetragene Versandart benutzt, sodass Sie SMTP nutzen können (was ich empfehle).
- Reply-to ist die Mailadresse des Users.

**Comment by oliverklee** [comment]
Ich habe das Ticket hier geschlossen, weil das die realty-Extension betrifft und wir bei Bedarf die Diskussion dort weiterführen sollten.
